language: node_js

node_js:
  - iojs
  - 0.10
  - 0.12

cache:
  directories:
    - node_modules
    - bower_components

env:
  global:
    - secure: O5W3ou9ETceXXB4soaUrN6VBOzqDTv41KNUfifUJt5m+jHT+XurZ46xR3u8dDTLaYP/hLobb9bsxlQ9L8YBlYFh1oj/7dp42MQda700CNNr840iWBdX+pXq6MeKggoRzj9ak06lTY3rlo1nQNvK+Fp/WOnASWeKpGGneWtQ0S+u+bXYHOkqPjL7fdE49hwOer4h8I2lVRRAytIHdl0qzc21vXA5JKl+3MuXB2DNXQlMo92iBLLSSNrfwttxnvxks42rcA/GSlNe+Zhq0AXd9WyaDQQPKTE9si8dBi+BjJedH/2SyF7y6J7fs+44yu5y9lQGY6fcSEfY9NxQgSWqageA9942juGwTa37G4yEU2jIZCVQcv1xZbbC0fMNnkB0Shd1Lek0qVMqvlmuGU7NHwozXZ9zavo1bMTAA7ASEigZKX8LhBg0FOaC0h1wH9TMVgpwtzTLXgqjzT2x/mWWOz4GCpsx9kh0C6iXYRLA596SkP9yaypDRwRxITHiY1PyHiQ0uYI5FeMaxclTmG+p1Yp0tmTqU8yXs0Vwu1Stwolw0BfRcZJQE//kX6FhUKPkLO6M4UNbOJ/z/aujvVPyNcL8c+lx+EkSLlmX9wv6IVdWDsRRD2gNtQCW4NHxj6NMA7G32PXQbdYQCrnmQ/pBOTJh3zLPVi9MhzNZLMm8qmng=
    - secure: e+3JSQWMWItWxTMrO5gNOIV73x/g//DmTkJI+s9Krc/I2YBWGHE6QaamaIyarxVBnlcu6c/6gn6OoZ3fv8oJCrFYecJNDVpelYm2BP0E40HVv9eIdxIHi585dHFL09L97meYqcESophI81NEvauUUpBUBdvoYNGi7T9KGuDbMpl3FMxjYuA/ksAv56TBtFdjsdbWdM8LTsSngwExXGtEMHxOTjqKvrGY/UWzHII+92dhLitS/3dhwFFvGn1t18Wiz0p1c54ELgPybiX+cVpcaveyq7lKXWJRpX9BsKUy7MEeucB9Xg/JfmeLwbmvyD4JC/zsMPih8vMbQ9kDlCXHsuym1xd6XCTTTTusLYa2kK/uSBkAlDucsUhbQl8ahFFje2VV+71XNDjgWbA45sDbJmdOoVHeVeoiuJpYS/yzPW8QTl6306vF3UOeYjW4NBOKU80UhX36STxRdeWopMCaw7KFxeyBIHpg+PN7R0wAZjXBnRsBHWM422M+6utD3dHVvs6bOWuBN5C/o5d6HfqcAXVe+jc5zPkGJvAByxqhfC8ZOOglGJISWi9zZ33nv6Mgw32eR8QAa8qIBxTufI7+XMeq3jqmH/sTROfXsROGirao69ZhVHzSto5AeQ/zu3UNtHbqoJLIUV3LmVzfIPTbcj81VOxMV6PwIwJKfTHDAXo=
