name: leodido/luhn.js

ui: mocha-bdd

browsers:
  - name: chrome
    version: 39..latest

capabilities:
  recordScreenshots: false
  videoUploadOnPass: false

browserify:
  - transform:
      name: babelify
      optional: runtime
